version: '3.8'

services:
  voxco-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voxco-dashboard
    ports:
      - "3000:3000"
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./pids:/app/pids
      - ./ports:/app/ports
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - voxco-network

networks:
  voxco-network:
    driver: bridge